version: "3.1"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db
    restart: always
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "3306:3306"
    restart: always
